name: quality

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: iv-one/goquality@v0
        with:
          command: publish
          args: --cover
